### PR TITLE
Delete setup.retry

### PR DESCRIPTION
**Pull request by brandonsavage**
Don't need this in the repo.

### CODE REVIEW

**Comment by jalefkowit** [comment]
Ack! How'd that get in there?!? Thanks!

**Comment by jalefkowit** [comment]
Merged this time, because I'm an idiot apparently

**Comment by brandonsavage** [comment]
Consider adding a .gitignore file and listing that file explicitly, so it doesn't make its way back in. =)

**Comment by jalefkowit** [comment]
There's a .gitignore already, but it didn't have setup.retry listed. Fixed now! Thanks!

**Pull request merged**
